format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/accessom2_restart.nml
  hashes:
    binhash: 9609da02b7885ab6017eb24fd179a320
    md5: 98b686c62f67e34cfe13425508604d7c
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ice/grid.nc
  hashes:
    binhash: 0cc806aa87cf3b0a8b3b5d8126c70b48
    md5: 189f572cf886440edd5ac6dab40df3d8
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ice/i2o.nc
  hashes:
    binhash: 4ea4622c1299cf5922c62b058e956ef4
    md5: d7abb7bfc3e488d54f619b01abc95e22
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ice/ice.restart_file
  hashes:
    binhash: d91cc821d280a08dbe5350b90b77bb7d
    md5: 31b91599e98dd329f15a878cb0bcef73
work/ice/RESTART/iced.1987-01-01-00000.nc:
  copy: true
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ice/iced.1987-01-01-00000.nc
  hashes:
    binhash: 4363f4db02dcd26741374fb1bf96d5ef
    md5: 18ddc5a354570d8e2aa2bc70ac318803
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ice/kmt.nc
  hashes:
    binhash: 0d6e1bb3001ae0520fb3bc83126469eb
    md5: a46c01045f519b9002b10f82df6ad376
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ice/monthly_sstsss.nc
  hashes:
    binhash: 168acced2400021041ea63ac1ddc43a7
    md5: e00d77cf7b519d9bbcfc8bea2e34ef8f
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ice/o2i.nc
  hashes:
    binhash: 17ea0df25126da9bb21ce3e2806985f4
    md5: efc2e7da4e2be9e6baf04e81bdbb2437
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ice/sicemass.nc
  hashes:
    binhash: 094270c3feac3c1e548301e21f40cd60
    md5: de7464f40ba2bef7fcb7b76d09e7648b
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ice/u_star.nc
  hashes:
    binhash: 6016362c39d24743124f01fd3dd82eab
    md5: 8f25843d0f0f8fe9e88e701e6233024b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_age.res.nc
  hashes:
    binhash: fe83ebbfa2998d8ed3aeb70fcc7ad9d7
    md5: 396c2eb42809cac8cce6539a448d8f54
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9c58e9c92598f3fb00a123049c8d1809
    md5: 90f5cd3feac6c6437efe07e575815185
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d6258408657cfbb33a109ec75b5557f0
    md5: d8299d2bd39c1311637748311e2acba6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_density.res.nc
  hashes:
    binhash: 7d240d631d8f6873345eb39649c60a2d
    md5: 18f760a6ab7b8900f3f61d8a275ef51c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3df321ff023d66ef6b99889a7358daed
    md5: 3cc6ba39cb9235211d1c0f9b5d5c327d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5fea13b48548bc42409b47aa42ccf668
    md5: 6623dcd2f881ae6d2b1f0680a068c35f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 75b356a58f2c1c6ad0b80891a5657023
    md5: 2b1b8cfb28bbd5cb92621ee8501a7a0f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_solo.res
  hashes:
    binhash: c09b2285723bb99ad213d9632635f708
    md5: ca3e899a610bd6f7751e20b83965b232
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 98debc305566386adb8b10661a451f45
    md5: ff3344414a89adae207c34fc6d0bfc4d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a62687561d1cb4cc442cc2f639aa6986
    md5: 8f782387c78aea431bab4b0a6cf265ff
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_tracer.res
  hashes:
    binhash: eb10d50c5e86bfef57ba6fa15bd57307
    md5: a332fb55d5731b97581b70ffbc541cdc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c4da4bdc31da0e64f3891f317c516645
    md5: f73f345df160b648550063adbff917ee
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/x77/aek156/access-om2/archive/01deg_jra55v140_iaf/restart115/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 10dcbedf30c677e91601bd4357c3715d
    md5: ef32aa7b38e310738ac79f429b1e3357
