format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/accessom2_restart.nml
  hashes:
    binhash: 0bb2f77f4853450f89e7f2e6e490c7c8
    md5: 6fd6a8382beacf9b5c9941eaab438a38
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ice/grid.nc
  hashes:
    binhash: f89c67163a9ca2a681f0bd5f54a3f210
    md5: 189f572cf886440edd5ac6dab40df3d8
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ice/i2o.nc
  hashes:
    binhash: 3a096dbe7e762986c361bc1f38d73135
    md5: 6396f0d4d0754e19991f0c3712c8caa3
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ice/ice.restart_file
  hashes:
    binhash: 6dae66815f16ed78a032b88f173c4050
    md5: a4550780e9c9722aafe4c8615443ebb7
work/ice/RESTART/iced.2022-10-01-00000.nc:
  copy: true
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ice/iced.2022-10-01-00000.nc
  hashes:
    binhash: 5c57b00b2c5e08e3d69857923a8a8bb3
    md5: 0bffe295a0824901c361190a75bcee73
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ice/kmt.nc
  hashes:
    binhash: 9f34c05b15bc921fd9f893e6081994be
    md5: a46c01045f519b9002b10f82df6ad376
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ice/monthly_sstsss.nc
  hashes:
    binhash: 642747205995ec5e0c3bc7c5488cd5bf
    md5: e00d77cf7b519d9bbcfc8bea2e34ef8f
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ice/o2i.nc
  hashes:
    binhash: 716d2f25ecb5599a111b5996fea9d739
    md5: e9bb9fe57ec7f551d6174af40a4d75b9
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ice/sicemass.nc
  hashes:
    binhash: e3d5d635a30403d9a1e37a6dfc27f586
    md5: 2f241d4a33cc254a4c72fb28e154641a
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ice/u_star.nc
  hashes:
    binhash: cc5ceb0d09bcb4500e495ca7f87ef70d
    md5: d0bcafbfd13dcbbe061ead7a2457d2a9
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/csiro_bgc.res.nc
  hashes:
    binhash: f23ee265f5e896d004117e63afaeff94
    md5: d8544729b83d3e64a6e6b13f2a7fa327
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: a472f21d65408061e69ebd8167848a5e
    md5: dd0686e1cf106f3c305c3923ca223174
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_age.res.nc
  hashes:
    binhash: c1da0d5430bcde2bf14b839e99bcbf2b
    md5: c1a476c35cc4acf4576f56fe080a349a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e37a72662e1f69074f4d5e6247ae6a25
    md5: ffcb8c9328b4488c0db12cef65117d24
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1d5f6d6aaf271f90f7780c4f9fc9a2e7
    md5: 777d2ef169896c5ee2b5fd8f2e3fa04d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_density.res.nc
  hashes:
    binhash: bd0da0c3664c53929bc1ea2de74dd0f8
    md5: 026eba4823f044cd958cb4902dd3894a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b8baab0e4908e30264154681b4d9dabd
    md5: bd9a5642388c25191d993365067568a0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 268495c70717085d476c5c106558d408
    md5: 9c59735e13fceb05b44d3dc3128db617
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5cc3bfe0762f051be89a582a042e914c
    md5: 32fb98a2ef157b265e2143042c4af166
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_solo.res
  hashes:
    binhash: 15baf20d6266e02dcb658366eb0487f0
    md5: a5c350c56b1f8c8016c8145262ed46b8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 367d076beae67e9c5b99e0e4bc1c4900
    md5: 65e74287b53d7903289171a33b499067
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3374a34745d08b25ac20beba456a255f
    md5: 436630fb6951701d53e48987abf71800
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_tracer.res
  hashes:
    binhash: fa92e303c8465bb457be9c994253c4ee
    md5: a9ae234d2b2347df827c8d8e5e592250
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a719737c23285acdfb240b15452c783c
    md5: f4667870241b96171fb1ef259c143738
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/v45/aek156/access-om2/archive/01deg_jra55v140_iaf_cycle4_jra55v150_extension/restart1006/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0515e55f7f0ce54bd179c7f344d1e4b1
    md5: 664118d97b6f21353302557cabb068a4
