format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/accessom2_restart.nml
  hashes:
    binhash: 404b8e9988da3b13a3b7ed930bc28cd6
    md5: 1e2df457d5bbcb76b397d9139001ecf3
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ice/grid.nc
  hashes:
    binhash: 1cb69f301298b54e00842a689f303e4b
    md5: 189f572cf886440edd5ac6dab40df3d8
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ice/i2o.nc
  hashes:
    binhash: 674deeef5156f57750bc68f440bf4d37
    md5: d1765aa371f986784513087097fabf0b
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ice/ice.restart_file
  hashes:
    binhash: aa9a160e4e727533ea309d6aaf5cb0d8
    md5: b42f104097cec85377ef9911edc1a542
work/ice/RESTART/iced.1980-07-01-00000.nc:
  copy: true
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ice/iced.1980-07-01-00000.nc
  hashes:
    binhash: 50dc6d2c87b4f519c5737b9752b9aed6
    md5: acadaf081fb209a1a445659d52b526de
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ice/kmt.nc
  hashes:
    binhash: 3f90c3588961bdc1a84644e3a6550442
    md5: a46c01045f519b9002b10f82df6ad376
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ice/monthly_sstsss.nc
  hashes:
    binhash: 6e75169d37bdd7e7e01afa1077d647a2
    md5: e00d77cf7b519d9bbcfc8bea2e34ef8f
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ice/o2i.nc
  hashes:
    binhash: 57a4f7035379e8209d841f9e52f9e3c0
    md5: d9428b6f8fc28419afe7220df37837e2
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ice/sicemass.nc
  hashes:
    binhash: 577487ee0eefc60ac013b68eef3721ea
    md5: 45f5447f55a7e51846c1edc4b72a2ba9
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ice/u_star.nc
  hashes:
    binhash: 21b84dee9b5592ff40a9f8bdfd865665
    md5: cea8972c0188739bcad2537ab282d98c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_age.res.nc
  hashes:
    binhash: ebaad9c2ce84772adc19494d69f03176
    md5: 93baa108afefad7ce6262bc87f73af26
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4db99ebd56d92fd05cdc552140dff0ad
    md5: 7d89991baa304000240f3babab183667
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 14f5b3673063b900e2e5935c0b7aa2f1
    md5: db26100f642cb7b214916a54c46862f9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_density.res.nc
  hashes:
    binhash: b0d7f79df0b4085064b1757798118ea8
    md5: 858715071f6729e70783d99f216afec9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 55a517248d920776a1c14e0a317e62cb
    md5: 0938b039a52ff12b27dbd0390c4e53b0
work/ocean/INPUT/ocean_passive.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_passive.res.nc
  hashes:
    binhash: 7deaa0f9c1816fdb13872b3f2cb48380
    md5: 39e29819ea3448d2a7f6de6818e3e513
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 962fd1d92feb6012a360e52bb449d0d9
    md5: b65970fa71cd67c447c35872e48d7f46
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cdce347c79c7b939dd7f6bcc666f34e5
    md5: 0bb1dd8cf870ad6df8156284290a3ef5
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_solo.res
  hashes:
    binhash: 7218a139047c856dfe7d737b233ae3a6
    md5: 816db924d36c2bfad6db111caa72748e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cdf4f9db100cb6efe92b07826c0d040f
    md5: e62d980d8410bcb989c9f09696496427
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ca2c84e4e45d052bd2f8373e8a5fd139
    md5: dc3afbb39f4fa293992552ee1d966900
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_tracer.res
  hashes:
    binhash: aa8da5a386979768cfb9f61c604374a0
    md5: ba2e9825dab779a84c7236fe4727c479
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_velocity.res.nc
  hashes:
    binhash: cb536521c0b615f3792d4764f8f68f85
    md5: 952f2e79a2c662d8d966f9fc47245f5e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/v45/akm157/access-om2/archive/01deg_jra55v140_iaf_cycle3_antarctic_tracers/restart577/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1e316e446aa83f9a502bcc8040b847c3
    md5: 40385e406da548157f3349fd4bb5359c
